version: '3'
services:  #services listet die ganzen container auf

  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: app
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  app: